-- Create USER table
CREATE TABLE "USER" (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    CREATED_TIME TIMESTAMP
);

-- Create TODO_LIST table
CREATE TABLE TODO_LIST (
    USER_ID INTEGER NOT NULL UNIQUE,
    CONTENT TEXT,
    CREATED_TIME TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES "USER"(ID)
);